# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    ports:
      - 3310:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      
    volumes:
      - ./conf:/etc/mysql/conf.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080