# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - 3311:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      
    volumes:
      - ./conf:/etc/mysql/conf.d
